### ISSUE TITLE
Add log verification to integration tests

### ISSUE THREAD

**Issue by aaron-prindle** [knative/build-pipeline#119]
## Expected Behavior
The integration tests should support viewing the logs for a Build containers invocation (Build -> hello world container -> container logs -> "hello world")

## Actual Behavior
Currently we are unable to view the logs for a container that is created by Build as once the container exits, it's logs cannot be queried.

## Possible Solutions
- Use streaming logs and `sleep` in our examples so that we have time to verify that the output we want verified is there 
- Persist logs somewhere so that once the container exits we can still read them (GCS or a k8s PVC)

**Comment by bobcatfish** [comment]
Related issue in knative/build about not being able to access logs: https://github.com/knative/build/issues/232

**Comment by bobcatfish** [comment]
An even more related issue in knative/build: https://github.com/knative/build/issues/9

**Comment by bobcatfish** [comment]
Implemented in #133
