### ISSUE TITLE
Find better name for `PipelineParams`

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#121]
## Expected Behavior
The name for the values in `PipelineParams` should be descriptive and should be pluralizable without causing laughter.

## Actual Behavior
The current name is `PipelineParams` and code-generator pluarlizes this as `pipelineparamses` #114 (https://github.com/kubernetes/code-generator/issues/53)

![image](https://user-images.githubusercontent.com/432502/46701756-aa463300-cbd5-11e8-8ffe-76a4919849ce.png)

## Additional Info
`PipelineParams` used to contain a grab bag of various parameters, but many of these are being moved into [Resources](https://github.com/knative/build-pipeline#resources) instead. At the moment it has been reduced to containing only:

* A service account to use to run the Pipeline (maybe we don't need this now that [resources can declare their own service accounts as needed?](https://github.com/knative/build-pipeline/blob/master/docs/pipeline-resources.md#git-resource)
* Result store endpoints

Some name ideas:
* `PipelineConfig`
* If we could reduce it to only containing result store endpoints, `ResultConfig`, `ResultStore`

**Comment by pivotal-nader-ziada** [comment]
Can we rename the type to `PipelineParam` and then the plural of it would be `PipelineParams`? All the other existing types have singular names (Task, Resource, ...) 
or even change the name completely, for example `PipelineConfiguration`

**Comment by abayer** [comment]
This has been vexing me lately as I try to write up and explain the Pipeline CRD model to others, particularly to anyone with a Jenkins background, since `PipelineParams` sure sounds like it's where you define parameters for a pipeline, but it's in fact just a narrow scope of parameter types, and not ones that change from run to run (unlike Jenkins' job parameters). So I'm a 👍 for `PipelineConfig` or some variant thereof.

**Comment by bobcatfish** [comment]
@abayer looks like in #263 we _might_ actually define arbitrary pipeline parameters too :O 

`PipelineConfig` still seems like a better name tho :thinking:
