### ISSUE TITLE
Design and implement behavior for multiple input sources

### ISSUE THREAD

**Issue by dlorenc** [knative/build-pipeline#123]
## Expected Behavior
A Task can accept multiple input resources, and produce multiple output resources.

## Actual Behavior

Today we're translating an input resource to a knative/build Source, which is simple but leaves us with a few limitations:
* We're limited to the Sources knative/build takes
* We're limited to one input Resource.

## Additional Info

Idea: translate the inputs and outputs to our own "steps" that we prepend and append to the BuildSpec. 

Should we have one input fetcher and one output uploader per input/output? Or one for all inputs and one for all outputs?

One for each seems elegant and would let us specialize them per-type, but init containers are limiting in that there is no parallelism and any failure causes the entire pod to fail.

One input and one output container would let us parallelize uploads/downloads and handle retries/failures a bit more elegantly across the Task.

**Comment by dlorenc** [comment]
Apologies if this issue already exists somewhere.

**Comment by bobcatfish** [comment]
Probably good to track this here anyway @dlorenc since we definitely need it!

This is the related issue in knative/build: https://github.com/knative/build/issues/392

**Comment by bobcatfish** [comment]
(Looks like you're looking at the knative/build issue @shashwathi so I'll assign this one to you too for now but let me know if you'd rather not have it assigned to you!)

/assign @shashwathi

**Comment by dlorenc** [comment]
It looks like @shashwathi is stuck on backwards compatibility in build. Should we handle this here, instead?

**Comment by bobcatfish** [comment]
> It looks like @shashwathi is stuck on backwards compatibility in build. Should we handle this here, instead?

After so much back and forth, @shashwathi I think that (contrary to what I've said before) we are embracing the idea of adding our own init containers that execute before `Build`'s init containers, so implementing this by adding containers for now seems a-ok.

**Comment by shashwathi** [comment]
@bobcatfish : https://github.com/knative/build/pull/451

**Comment by pivotal-nader-ziada** [comment]
@dlorenc can you please close that? it's done as part of #232 and the PR in build https://github.com/knative/build/pull/451

**Comment by dlorenc** [comment]
Closing as this was handled in build.

**Comment by bobcatfish** [comment]
Amaaaaazing, thanks @shashwathi :D :D :D :tada:
