### ISSUE TITLE
Extend TaskRun Unit Tests to Cover All Possible Cases

### ISSUE THREAD

**Issue by aaron-prindle** [knative/build-pipeline#140]
## Expected Behavior
Currently the TaskRun unit tests only cover that a Build is generated from a Task and that the Build has the correct BuildSpec.  The following additional  cases should be added:

- [ ] taskrun w/ a build that isn't done
Actual Behavior: updates status of the taskrun to mirror build
- [ ] task w/ a build that is done
Actual Behavior: logs that the taskrun finished
- [ ] taskrun w/ no referenced task
Actual Behavior: errors

**Comment by pivotal-nader-ziada** [comment]
@bobcatfish @aaron-prindle i think this issue can be closed now based on #159

**Comment by bobcatfish** [comment]
Nice sounds good! Thanks @shashwathi :D And thanks for the clean up @pivotal-nader-ziada

**Comment by pivotal-nader-ziada** [comment]
@aaron-prindle  you will manually need to close this issue since the PR didn't say `fixes` and you are creator of the issue
