### ISSUE TITLE
Create solution for making logs available when running Tasks

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#143]
## Expected Behavior
After running a Task, it should be simple to get the logs that it has produced.

## Actual Behavior
You can try to get the logs from the init container, however if the pod has been deleted, the logs are deleted with it. _Sometimes_ you can get these logs but most of the time the pod is deleted and the init container logs vanish with it, though the other container logs are kept by k8s.

## Steps to Reproduce the Problem

  1. Run a Task (todo: #22 we need a simple walkthrough to link here!!)
  2. Try to view the logs by getting them from the init container (see [steps 5+ here](https://github.com/knative/docs/blob/master/build/creating-builds.md#creating-and-running-a-build))
  3. You _may_ see the logs or you may see an error about not being able to find `docker://somethingsomething`

## Additional Info
- knative/build main issue: https://github.com/knative/build/issues/9
- another discussion in knative/build https://github.com/knative/build/issues/232
- https://github.com/knative/build-pipeline/issues/119 issue where we used volume mounts for our integration tests to work around this
- https://github.com/knative/build-pipeline/issues/107 functionality we ultimately want

**Comment by bobcatfish** [comment]
I think you might be working on this @tejal29 , should I assign it to you?

**Comment by tejal29** [comment]
yes thanks!

**Comment by bobcatfish** [comment]
Fixed in #167
