### ISSUE TITLE
Pipeline Validation - Controller Side

### ISSUE THREAD

**Issue by dlorenc** [knative/build-pipeline#162]
## Expected Behavior
Pipeline CRDs can be validated semantically. This includes:
1. Tasks in the Spec exist and are valid
2. All required inputs for all Tasks are bound
3. All required outputs for all Tasks are bound
4. All required parameters for all Tasks are provided
5. Resources used by a pipeline exist and are valid

Note that 2

## Actual Behavior
Validation is superficial only. TaskRefs are validated, but not dereferenced. Missing Tasks or misconfigured tasks are not made visible until the pipeline (and Tasks) is actually run.

## Additional Info
This issue should track the design of this validation (where it should live) as well as the implementation.

**Comment by bobcatfish** [comment]
@shashwathi I changed the requirements of this task a little, I think they are just more specific now.

However, one option would be to not dereference any Tasks in the Pipeline controller, and instead do all the verification in the PipelineRun controller (#189). In some ways this might make more sense, to prevent an order being imposed (e.g. you must create a referenced Task before creating the Pipeline)
