### ISSUE TITLE
Build steps that rely on entrypoint wont work properly with logging, i.e. Command is required currently

### ISSUE THREAD

**Issue by aaron-prindle** [knative/build-pipeline#175]
## Expected Behavior
A BuildStep that uses an in image with an executes normally as it would if ran standalone

## Actual Behavior
The entrypoint modification done for the logging will "blowup" the user defined entypoint leaving the container not running correctly

## Steps to Reproduce the Problem

  1.  Create an image w/ only an "Entrypoint" and no "Command"
  2. Specify that image as a BuildStep
  3. Run the Build
  4. BuildStep will not run as expected

## Possible Fix
We can update the controller to inspect the image's `Entrypoint` and use that if required.

**Comment by tanner-bruce** [comment]
I have PR #183 open with an initial attempt at resolving this.
