### ISSUE TITLE
Use event recorder to verify failure cases instead of logs

### ISSUE THREAD

**Issue by shashwathi** [knative/build-pipeline#186]
In [pipeline run tests](https://github.com/knative/build-pipeline/blob/master/pkg/reconciler/v1alpha1/pipelinerun/pipelinerun_test.go#L277) log observer is used to verify certain negative test cases. We could instead refactor to inject fake recorder into controller and check the events generated.

## Expected Behavior
No log observer in unit tests

## Actual Behavior
Log observer is used

**Comment by wtam2018** [comment]
I'm interested in working on this issue.   How do I assign myself?   I don't seem to have permission.

**Comment by vdemeester** [comment]
/assign @wtam2018 
(If the bot complains, it's no big deal, people will know you're working on this one :wink:)

**Comment by bobcatfish** [comment]
Unfortunately we can only assign issues to ppl who are members of the knative repo, but we'll consider this issue assigned to you anyway!

I've created https://github.com/knative/build-pipeline/pull/242 to add some instructions to our CONTRIBUTING.md about what to do in this situation: basically if you add a comment expressing your intent to work on an issue, we'll consider it assigned to you.

Thanks for taking this on @wtam2018 !! :heart:

**Comment by markusthoemmes** [comment]
Seems to be done judging by the merged PR?

**Comment by vdemeester** [comment]
@markusthoemmes you are right !
/close
