### ISSUE TITLE
PipelineRun Validation - Controller Side

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#189]
## Expected Behavior
PipelineRun CRDs can be validated semantically.

PipelineRuns are pretty simple, so this is pretty much just making sure all referenced CRDs exist.

## Actual Behavior
Validation is superficial only. No referenced objects are dereferenced in the webhook.

## Additional Info
#162 is related work for the Pipeline, #188 is the same work for TaskRuns.

**Comment by shashwathi** [comment]
@bobcatfish : This issue is related to https://github.com/knative/build-pipeline/issues/162 
PR: https://github.com/knative/build-pipeline/pull/192
