### ISSUE TITLE
EntrypointImage should be configured instead of hard-coded.

### ISSUE THREAD

**Issue by zhujian7** [knative/build-pipeline#203]
## Expected Behavior
Make [EntrypointImage](https://github.com/knative/build-pipeline/blob/master/pkg/reconciler/v1alpha1/taskrun/resources/entrypoint.go#L34) configurable.
Because in some customer environment, Google Container Registry is hard to connect. Unfortunately they can not pull the container even though they have their own docker registry in local area network.

## Actual Behavior
[EntrypointImage](https://github.com/knative/build-pipeline/blob/master/pkg/reconciler/v1alpha1/taskrun/resources/entrypoint.go#L34) is hard-coded as `gcr.io/k8s-prow/entrypoint@sha256:7c7cd8906ce4982ffee326218e9fc75da2d4896d53cabc9833b9cc8d2d6b2b8f`

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Additional Info
/cc @bobcatfish @pivotal-nader-ziada

**Comment by pivotal-nader-ziada** [comment]
It would be even better if this `entrypoint` image is a custom image that is built in the pipeline project and not using the one from `Prow`

**Comment by zhujian7** [comment]
Well, what i am concerned about is whether i can execute the pipeline well,  which need to pull the `entrypoint` image from my **local docker registry** firstly.
And i think, if I understand the `entrypoint image` correctly, it is not very necessary to cost time to build the image in the pipeline as the image is stable at most time.

**Comment by bobcatfish** [comment]
Great point, thanks for opening this issue @zhujian7 !

I think at the moment we don't load any configuration dynamically for the controllers (correct me if I'm wrong!), so we'll need to add that. There should be some precedent in the other knative controllers tho I think.

**Comment by pivotal-nader-ziada** [comment]
My point was not to create the image in the pipeline, I meant to say it should be part of the `build-pipeline` repo and therefore available for you to build and host locally. This is in addition to make the configurable, sorry for not being clear.

**Comment by zhujian7** [comment]
@pivotal-nader-ziada That would be great! thank you.
> it should be part of the build-pipeline repo and therefore available for you to build and host locally

And please forgive me for my poor engilish, sorry for my misunderstanding.

**Comment by pivotal-nader-ziada** [comment]
Thanks for the issue @zhujian7 and no worries at all

Would you be interested in making a pr for this change?

**Comment by zhujian7** [comment]
Thanks, I am interested to give it a try in my free time.

**Comment by tanner-bruce** [comment]
Could this be done by an annotation like `pipeline.knative.dev/entrypoint-image"` added to the `PipelineRun`?

**Comment by bobcatfish** [comment]
> Could this be done by an annotation like pipeline.knative.dev/entrypoint-image" added to the PipelineRun?

You _could_ but i think a `ConfigMap` is how this is done for other projects, e.g. https://github.com/knative/build/blob/master/config/config-logging.yaml
