### ISSUE TITLE
PipelineRun Controller Validation - Output Binding Issue

### ISSUE THREAD

**Issue by aaron-prindle** [knative/build-pipeline#213]
## Expected Behavior
Currently there is a bug in the PipelineRun Controller Validation as noted in https://github.com/knative/build-pipeline/pull/192#discussion_r229856526.  This allows for Outputs to not have proper Resource bindings.  A test for correctly working correct-output-source-bindings (in addition to the bad-output-source-bindings test we currently have) should catch this issue as currently nothing is added to outMapping here:
https://github.com/knative/build-pipeline/blob/master/pkg/reconciler/v1alpha1/pipelinerun/validate.go#L99

## Actual Behavior
Outputs mappings should be checked in a PipelineRun.  Currently, as nothing is added to the outMapping, it is not possible to have a verified PipelineRun that has Resource mapping

## Steps to Reproduce the Problem

  1. Create a Resource
  2. Create a Task requiring an Output with a ResourceRef
  3. Create a TaskRun referencing the created Resource

**Comment by aaron-prindle** [comment]
I can refactor the PipelineRun/TaskRun validation to share code which should fix this, putting this here as a reminder.

**Comment by aaron-prindle** [comment]
Also should address:
https://github.com/knative/build-pipeline/pull/208#pullrequestreview-170491372

**Comment by bobcatfish** [comment]
I'm touching this code anyway and I can't help myself so I'll take this on

**Comment by bobcatfish** [comment]
> Outputs mappings should be checked in a PipelineRun. Currently, as nothing is added to the outMapping, it is not possible to have a verified PipelineRun that has Resource mapping

After looking at the code more closely, it turns out that the code _will_ make sure that there is a resource specified for the outputs, the missing bit is that the type won't be checked.
