### ISSUE TITLE
Add release automation

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#219]
## Expected Behavior
We should have automation that will build and push:

* Images for our controllers to a registry (GCR?)
* Yaml for deploying to a known place (GCS?)

## Actual Behavior
Currently the only way to setup the Pipeline is to run `ko` [as described in the DEVELOPMENT guide](https://github.com/knative/build-pipeline/blob/master/DEVELOPMENT.md#install-pipeline)

## Additional Info

See [release script for knative/serving](https://github.com/knative/serving/blob/master/hack/release.sh), invoked [by prow](https://github.com/knative/test-infra/blob/master/ci/prow/config.yaml#L1456).

**Comment by ImJasonH** [comment]
Done in #241 

cc @adrcunha

**Comment by adrcunha** [comment]
Now that the release script exists, we just need a Prow cron job to create nightlies.

**Comment by bobcatfish** [comment]
Can I assign this one to you @ImJasonH ? :D

**Comment by bobcatfish** [comment]
Hey @adrcunha , anything left to do here? If not, where can we see the releases?

**Comment by adrcunha** [comment]
Nightly releases were re-enabled on 12/5. You can track them here:

https://testgrid.knative.dev/knative-build-pipeline#release

Nightly releases are published to:

gs://knative-nightly/build-pipeline/latest/release.yaml

and

gs://knative-nightly/build-pipeline/previous/<vYYYYMMDD-commithash>/release.yaml

Images are published to

gcr.io/knative-nightly/github.com/knative/build-pipeline/...

And are tagged `latest` and `vYYYYMMDD-commithash` as appropriate.
