### ISSUE TITLE
Create integration tests for `knative/serving` with PipelineRun + TaskRun

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#227]
## Expected Behavior
In github.com/knative/serving, a [`Configuration`](https://github.com/knative/serving/blob/master/docs/spec/spec.md#configuration) (see [overview](https://github.com/knative/serving/blob/master/docs/spec/overview.md)) can contain a `Build`, which can be used to build the image which will be used in the `Revision`.

Thanks to [duck typing](https://docs.google.com/document/d/16j8C91jML4fQRQPhnHihNJUJDcbvW0RM1YAX2REHgyY/edit) (viewable by members of [knative-dev@](https://groups.google.com/forum/#!forum/knative-dev)), it should be possible to use a `PipelineRun` or a `TaskRun` instead.

We should have [e2e tests](https://github.com/knative/serving/blob/master/test/adding_tests.md) (maybe even confromance tests?) inside `knative/serving` which verify that `Build` can be swapped out for a `TaskRun` or a `PipelineRun`.

## Actual Behavior

While this theoretically should work, we haven't tried it and there is nothing to ensure this keeps working over time.

## Steps to Reproduce the Problem

The test should:
  1. Create a Configuration where the [spec.build](https://github.com/knative/serving/blob/master/docs/spec/spec.md#configuration) contains a TaskRun definition that uses a Task which builds the image which the Revision will use.
  2. Deploy the Configuration
  3. Verify that the image was built and deployed

Repeat the same for a `PipelineRun`.

## Additional Info
Part of #147

**Comment by pivotal-nader-ziada** [comment]
@bobcatfish I think we need to have a release of `pipeline` first before we can a `release.yaml` in serving and try using it, wdyt

**Comment by bobcatfish** [comment]
After discussing with @pivotal-nader-ziada @shashwathi @ImJasonH we think we can go forward for now by vendoring Pipelines at an arbitrary nightly release (maybe take a look at how serving currently vendors Build as well).

**Comment by tejal29** [comment]
@vdemeester  are you actively working on this one? I am looking to jump in on 0.4 release milestone issues.
