### ISSUE TITLE
TestGetRemoteEntrypoint makes real HTTP requests

### ISSUE THREAD

**Issue by ImJasonH** [knative/build-pipeline#268]
## Expected Behavior

I can run Go tests without a connection to the internet.

## Actual Behavior

`TestGetRemoteEntrypoint` panics because the registry can't be found, and the error doesn't result in a `t.Fatal`

## Steps to Reproduce the Problem

  1. Disconnect wifi
  2. `go test ./...`

## Additional Info

This test would also fail if the Kaniko image changed its entrypoint.

Unit tests shouldn't depend on external state. Instead, HTTP requests should be mocked out in the client, or even better, the image should be served from a local HTTP server that's spun up in the test, using `net/http/httptest`.

**Comment by bobcatfish** [comment]
That was amazing turnaround time @vdemeester XD!!!
