### ISSUE TITLE
Add the ability to cancel/abort a running PipelineRun without deleting the PipelineRun itself.

### ISSUE THREAD

**Issue by abayer** [knative/build-pipeline#272]
## Expected Behavior

A user can cancel or abort a PipelineRun, causing all TaskRuns (and their associated Builds) within the PipelineRun to also cancel/abort, while preserving the PipelineRun and associated TaskRuns/Builds for reporting purposes.

## Actual Behavior

PipelineRuns can only be canceled by deleting the CRD, eliminating any record of the canceled run.

## Additional Info

This will require changes to Build CRD to allow for canceling a running Build.

Related to #222

**Comment by abayer** [comment]
woo! I've been working on #222 off and on over the last week, and got stuck on figuring out how to cancel/abort a `TaskRun` (and associated `Build`) in the first place, so I'll be watching this closely. =)

**Comment by vdemeester** [comment]
@abayer ah :upside_down_face: well, let's see if I'm hitting a wall too or not :angel: :stuck_out_tongue_closed_eyes:

**Comment by abayer** [comment]
Well, at least then I wouldn't be the only one hitting a wall on this. =)

**Comment by vdemeester** [comment]
I think we can close this one as #510 is merged

/close
