### ISSUE TITLE
Add validation to controller for Task CRD

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#29]
## Expected Behavior

When someone creates a [Task](https://github.com/knative/build-pipeline#task) in a k8s cluster (e.g. with [kubectl apply](https://github.com/knative/build-pipeline/blob/master/DEVELOPMENT.md#installing-and-running), the controller should make sure every field is valid.

This should include verifying as many fields as possible, e.g. verifying connectivity with any endpoints, if there are any references, verifying that those actually exist in the system, etc.

Task is defined here: https://github.com/knative/build-pipeline/blob/master/pkg/apis/pipeline/v1beta1/task_types.go

Any additional fields included should cause a failure (e.g. if a typo is made when defining a known field).

## Actual Behavior

Some basic validation is applied, e.g. that required fields are present and that fields are in the correct format (e.g. string vs. int), but that's it.

## Steps to Reproduce the Problem

1. [Deploy the Pipeline CRDs to your k8s cluster](https://github.com/knative/build-pipeline/blob/master/DEVELOPMENT.md#installing-and-running)
2. Create an instance that has invalid fields, e.g. a malformed URL or a typo in one of the fields.
3. Apply the instance with `kubectl apply -f` and notice that the controller does not complain

## Additional Info
_Blocked by #19_

**Comment by bobcatfish** [comment]
/assign @dlorenc 

@dlorenc btw you should also take a look at #83 before you get started, where @pivotal-nader-ziada is adding skeleton webhooks

**Comment by dlorenc** [comment]
Closing this for now. We can always add more validation, but we have the basics.
