### ISSUE TITLE
Once a Run finishes, it should never be invoked again

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#299]
## Expected Behavior

Once a `PipelineRun` or `TaskRun` completes, it should never be invoked again. It should be considered completed (i.e. it's a one-off).

## Actual Behavior

You can trigger a re-reconciliation of an existing `PipelineRun` or `TaskRun` by changing them or by changing any resources that were created by their reconcilers.

* A `PipelineRun` will create a `TaskRun`, so changing either of those will trigger re-reconciliation.
* A `TaskRun` will create a `Build` (until #252) so changing either of those will trigger re-reconciliation.

## Steps to Reproduce the Problem

1. Create a PipelineRun (e.g. see [the examples](https://github.com/knative/build-pipeline/tree/master/examples#examples))
2. Wait for it to complete (the example pipeline takes a while, so you could modify it to just echo hello world if you want it to be faster)
3. Find one of the created `TaskRun`s and delete it
4. Observe that the `TaskRun` is re-created.

**Comment by abayer** [comment]
So yeah, this plays into #279 pretty clearly, but I think it also has relevance in #222 and to an underlying matter - we don't have a way to casually look at a `PipelineRun` and see that it's "done". I'm trying to get familiar enough with how status works here and over in Build (where they do have `isDone`) to see if I can come up with a solution.

**Comment by bobcatfish** [comment]
> I'm trying to get familiar enough with how status works here and over in Build (where they do have isDone) to see if I can come up with a solution.

Note that while we can add conditions to the status, we probably have to keep the existing one as-is due to [the duck typing contract](https://docs.google.com/document/d/16j8C91jML4fQRQPhnHihNJUJDcbvW0RM1YAX2REHgyY/edit).

But whatever works for `Build` should work here! :D

Can I assign this one to you @abayer ?

**Comment by abayer** [comment]
Yup! Hopefully I'll make some progress before Kubecon. =)

**Comment by bobcatfish** [comment]
awwwwesoooome

thanks @abayer !
