### ISSUE TITLE
Update `knative/docs` with build-pipeline docs

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#304]
## Expected Behavior
In version 0.3 of `knative`, we'd like to release `build-pipeline`, which means that the docs repo docs on Build (https://github.com/knative/docs/tree/master/build) should talk about `build-pipeline`.

I propose that we do this:
* Add all of the markdown files at https://github.com/knative/docs/tree/master/build to this repo
* Update those docs to have the corresponding info in a post Build -> Task world
* As part of our official versioned releases (relevant to #72) we update `knative/docs` with the corresponding version of these docs from the repo

This way:
* `knative/build-pipeline` contains docs which are versioned alongside the code
* `knative/docs` contains the docs as of the most recent release

## Actual Behavior

It looks like the docs at https://github.com/knative/docs/tree/master/build are updated manually and don't have a clear process that ties them to the build + buildtemplate repos (@ImJasonH correct me if I'm wrong!)

## Additional Info
Blocked by the epic #147

**Comment by vdemeester** [comment]
@bobcatfish @ImJasonH for the time being, shouldn't we have both docs (`build` and `build-pipeline`) side by side ?

**Comment by bobcatfish** [comment]
> @bobcatfish @ImJasonH for the time being, shouldn't we have both docs (build and build-pipeline) side by side ?

Good question!

I think it depends on where we land with [the build task migration milestone](https://github.com/knative/build-pipeline/milestone/4) before the 0.3 release: If we're in a place where we feel confident asking folks to officially move from Build -> Task in that release, I think it could make sense to remove the Build docs entirely. (Or maybe in that case we should move the Build docs, but keep them around and make it clear they are for Knative 0.2 only @vdemeester ?)

Of course if we don't finish the milestone by 0.3 we should have both for sure.

**Comment by vdemeester** [comment]
> I think it depends on where we land with [the build task migration milestone](https://github.com/knative/build-pipeline/milestone/4) before the 0.3 release: If we're in a place where we feel confident asking folks to officially move from Build -> Task in that release, I think it could make sense to remove the Build docs entirely. (Or maybe in that case we should move the Build docs, but keep them around and make it clear they are for Knative 0.2 only @vdemeester ?)

Yeah I would definitely keep them around for a small while (with some sort of "warning new work is happening on pipeline) to make sure current content about knative (build) still exists somewhere (aka links to the docs repository targeting build, etc.)

**Comment by bobcatfish** [comment]
Looks like the toughest part of doing this is that for `build`, `knative/docs` has some fairly detailed API docs and also walk throughs which I'll need to make `pipeline` versions of:

* https://github.com/knative/docs/blob/master/build/build-templates.md
* https://github.com/knative/docs/blob/master/build/builds.md
* https://github.com/knative/docs/blob/master/build/creating-builds.md

**Comment by bobcatfish** [comment]
Re. doc versioning, looks like this is something the docs working group is taking care of already: https://github.com/knative/docs/blob/master/doc-releases.md
