### ISSUE TITLE
ServiceAccount of task are always overriden by TaskRun

### ISSUE THREAD

**Issue by vdemeester** [knative/build-pipeline#305]
## Expected Behavior

Given a Task that uses a `serviceAccount` and a `TaskRun` that doesn't, the `BuildSpec` will contains no serviceaccount (and thus uses the default one). The `TaskRun` *always* override the serviceAccount defined in the `Task`

## Actual Behavior

Given a Task that uses a `serviceAccount` and a `TaskRun` that doesn't, the `BuildSpec` should contains the `Task` serviceAccount instead of none/default.

## Steps to Reproduce the Problem

1. Create a sample task with a serviceAccountName
2. Create a taskrun with no serviceAccount that refers this Task
3. Look at the build/pod spec, the serviceAccount is the default one

## Additional Info

/kind bug
/assign

**Comment by vdemeester** [comment]
Discovered that while working on a follow-up for https://github.com/knative/build-pipeline/pull/285 (adding tests on it)

**Comment by bobcatfish** [comment]
Thanks for writing this up _AND_ fixing it @vdemeester :D
