### ISSUE TITLE
Add ability to embed Resource declaration also when embedding Tasks in TaskRuns

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#313]
## Expected Behavior

In #262 @pivotal-nader-ziada made it possible to embed a Task Spec into a `TaskRun` - this way you can create a `TaskRun` without needing to create a `Task` first - the goals here are:

1. Make it easy to migrate from knative/build to Task/TaskRun
2. Support the use case where `Builds` are embedded into specs in knative/serving and are self contained

It should be possbile to put _all_ of the info required for a `TaskRun` into a `TaskRun.spec` without requiring any additional resources to exist first.

## Actual Behavior

You can embed a Task spec in a TaskRun, but the Resources the TaskRun refers to must exist at the time of the TaskRun creation.

This means if you embedded a TaskRun in a knative/serving spec, you'd have to have created the required Resources beforehand.

## Additional Info

[Discussion about resources in the PR](https://github.com/knative/build-pipeline/pull/262#discussion_r237274362)

**Comment by bobcatfish** [comment]
(Build functionality needs specifically GCS + Git Resource types)

Can make sense to work on alongside migrating yaml tests (#302)

**Comment by shashwathi** [comment]
@bobcatfish : I have added a design doc to discuss proposed solutions. Please comment on it and we can get better alignment 👍 

https://drive.google.com/open?id=1BQDfihryPT25_kyBX0pmilBaFsASkZBlbRsUDF1RUew

**Comment by bobcatfish** [comment]
Great write up @shashwathi ! I'm having trouble picking one approach over the other, so I'm interested to hear what other ppl (particularly @ImJasonH ) think.

Also would like to understand more about whether we intend to support this indefinitely or if it's more of a temporary stepping stone @ImJasonH .

**Comment by ImJasonH** [comment]
@bobcatfish I think we should assume Serving will want the feature for the foreseeable future. Left comments on the doc. I like `resourceSpec`. 👍

**Comment by bobcatfish** [comment]
I was definitely thinking only about migration and not thinking about the serving use case at all 🤦‍♀️ I'm on board with the `resourceSpec` solution, especially if this is long term!

For handling the GCS type, I'm leaning toward adding a new resource type specifically for the `build` GCS functionality.

**Comment by bobcatfish** [comment]
@tejal29 to tackle the new GCS resource, maybe in a separate issue

**Comment by bobcatfish** [comment]
Looks like we've to a separate issue for the GCS resource in #415, any objections to closing this one @shashwathi ? :D

**Comment by shashwathi** [comment]
Feel free to close this issue @bobcatfish

**Comment by bobcatfish** [comment]
awesome :D :tada:
