### ISSUE TITLE
Add validation for PipelineRun CRD

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#32]
## Expected Behavior

When someone creates a [PipelineRun](https://github.com/knative/build-pipeline#pipelinerun) in a k8s cluster (e.g. with [kubectl apply](https://github.com/knative/build-pipeline/blob/master/DEVELOPMENT.md#installing-and-running), the controller should make sure every field is valid.

This should include verifying as many fields as possible, e.g. verifying connectivity with any endpoints, if there are any references, verifying that those actually exist in the system, etc.

PipelineRun is defined here: https://github.com/knative/build-pipeline/blob/master/pkg/apis/pipeline/v1beta1/pipelinerun_types.go

Any additional fields included should cause a failure (e.g. if a typo is made when defining a known field).

## Actual Behavior

Some basic validation is applied, e.g. that required fields are present and that fields are in the correct format (e.g. string vs. int), but that's it.

## Steps to Reproduce the Problem

1. [Deploy the Pipeline CRDs to your k8s cluster](https://github.com/knative/build-pipeline/blob/master/DEVELOPMENT.md#installing-and-running)
2. Create an instance that has invalid fields, e.g. a malformed URL or a typo in one of the fields.
3. Apply the instance with `kubectl apply -f` and notice that the controller does not complain

## Additional Info
_Blocked by #19_

**Comment by pivotal-nader-ziada** [comment]
@shashwathi @bobcatfish I think this is done now
