### ISSUE TITLE
Entrypoint cache should cache by digest

### ISSUE THREAD

**Issue by ImJasonH** [knative/build-pipeline#333]
When we lookup entrypoints for remote images, we cache it for later lookups. But, we cache by the _requested_ image name, and not the resolved image by digest.

So if a user changes the entrypoint to an image without changing its tag, the new entrypoint might not get picked up since it will already have been cached. Instead, we should always resolve the image tag to its digest, then lookup in the cache whether that digest's entrypoint is already known.

Since we'd be resolving the image tag -> digest before running the build, we can also request the exact image by digest when we run the pod. This removes a race condition where the entrypoint changes between the time the build is requested and the time the step starts running. We should include builder image digests in `TaskRunStatus` for visibility.

To avoid looking up the digest for a tag each time, we could keep a separate cache for that lookup that expires after some (configurable) amount of time.

**Comment by bobcatfish** [comment]
Yep I think so @Zyqsempai ! Note that @mathspanda is converting our existing cache to lru in https://github.com/knative/build-pipeline/pull/350 so we can probably build on that :D

**Comment by Zyqsempai** [comment]
@bobcatfish Then, it will be good to merge his PR asap;)

**Comment by zhyuri** [comment]
Hi @Zyqsempai , are you working on this issue?

Just want to confirm because I'm also looking for some issues to work on.

**Comment by Zyqsempai** [comment]
@zhyuri Yep, i do. Sorry.

**Comment by bobcatfish** [comment]
Thanks @Zyqsempai !!! :tada::tada::tada:
