### ISSUE TITLE
Nightly releases not published since 12/18/2018

### ISSUE THREAD

**Issue by mgreau** [knative/build-pipeline#356]
## Expected Behavior

Each day a `release.yaml` is published to https://console.cloud.google.com/storage/browser/knative-nightly/build-pipeline/latest and the Images are published to
https://console.cloud.google.com/gcr/images/knative-nightly/GLOBAL/github.com/knative/build-pipeline

## Actual Behavior

The latest `release.yaml` file and images have been published 10 days ago on **12/18/18, 9:58:59 AM UTC+1**

## Additional Info
Looking at https://testgrid.knative.dev/knative-build-pipeline#release it seems to due to a permission issue:
```
W1228 08:57:07.012] 2018/12/28 08:57:07 Using base gcr.io/distroless/base:latest for github.com/knative/build-pipeline/cmd/kubeconfigwriter
W1228 08:57:07.188] 2018/12/28 08:57:07 error processing import paths in "config/webhook.yaml": no token in bearer response:
W1228 08:57:07.188] {"errors":[{"code":"DENIED","message":"Token exchange failed for project 'knative-nightly'. Caller does not have permission 'storage.buckets.get'. To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control"}]}
W1228 08:57:07.213] Run: ('/workspace/./test-infra/jenkins/../scenarios/../hack/coalesce.py',)
E1228 08:57:07.359] Command failed
I1228 08:57:07.360] process 627 exited with code 1 after 25.0m
E1228 08:57:07.360] FAIL: ci-knative-build-pipeline-nightly-release
```

**Comment by adrcunha** [comment]
There is another issue preventing the nightly builds:

```
W1228 08:52:04.362] /go/src/github.com/knative/build-pipeline/test/e2e-common.sh: line 75: ((: >> Waiting for tests to finish
W1228 08:52:04.363] >> Checking test results: syntax error: operand expected (error token is ">> Waiting for tests to finish
```

This should be fixed by #358.

**Comment by adrcunha** [comment]
#359 takes care of the account service issue.

**Comment by bobcatfish** [comment]
Looks like this is fixed at https://storage.googleapis.com/knative-nightly/ (thanks @vdemeester !)

**Comment by mgreau** [comment]
Thanks for the fix 👍
