### ISSUE TITLE
Design: Templating

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#36]
The work for this task is to design this feature and present one or more proposals (before implementing).

## Expected Behavior
In our examples, we use the syntax `${something}` to reference things, but we don't have a clear model for what can and can't be referenced.

* [Tasks](https://github.com/knative/build-pipeline#task) should be able to reference anything from their inputs or outputs
* [Pipelines](https://github.com/knative/build-pipeline#pipeline) should be able to reference outputs of Tasks in the Pipeline and a [PipelineParams](https://github.com/knative/build-pipeline#pipelineparams)

For example, referencing both parameters and cluster bindings within a [Task](https://github.com/knative/build-pipeline#task):
https://github.com/knative/build-pipeline/blob/master/examples/deploy_tasks.yaml#L47

## Actual Behavior
This exists in our examples but it's not clear exactly what can and can't be referenced.

**Comment by bobcatfish** [comment]
TODO: should this also cover References, or should we create a separate issue for that? e.g.:

- TaskRuns refer to Tasks
- PipelineRuns refer to Pipelines and PipelineParams
- Pipelines refer to Tasks when linking Task outputs with Inputs

Specifically how the [object references](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#object-references) will work.

**Comment by pivotal-nader-ziada** [comment]
Where are you expecting the values for the templated variables to be provided from? the cli or from a file? That would mean we can't directly apply these yaml files using kubectl.  
We will probably have to build something custom, as part of the cli, to replace them. Maybe using go template package.

**Comment by aaron-prindle** [comment]
Currently the idea would be that the yaml that is submitted by kubectl does not have the templated values templated.  The templating would be done in the controller, similar to how variable templating is currently done in knative/build:
https://github.com/knative/build-templates/blob/master/kaniko/kaniko.yaml#L17
https://github.com/knative/build/blob/3e2b7e1ae179216063f52b75c7b75e5e29742539/pkg/builder/common.go#L55

We are still working through all the values that would need templating and this idea/method is definitely open for discussion.

**Comment by pivotal-nader-ziada** [comment]
I believe the way the build works is the the build yaml file will have the values that will be applied to the variables in the template. 
That makes sense in the case of `task templates` that would get values for their variables from the pipeline, but would be nice to also think about some dynamic option such as the pipeline replacing their template variables from env variables or a config map

**Comment by bobcatfish** [comment]
[This is the design doc for both templating and references](https://docs.google.com/document/d/1bJLE1E6skPjr1rGtSR0gAXdMaWryXTDTVnCPIKJkRBk), shared with members of  [knative-dev@](https://groups.google.com/forum/#!forum/knative-dev).

See also #38
