### ISSUE TITLE
Make use of CRD status subresource

### ISSUE THREAD

**Issue by dprotaso** [knative/build-pipeline#364]
See: https://github.com/knative/build/pull/516

This will allow us to drop the webhook generation logic in `knative/pkg` in future releases

For context [here's a comment](https://github.com/knative/serving/issues/643#issuecomment-450905774) about the migration path to drop this webhook logic in `knative/serving`

**Comment by bobcatfish** [comment]
lol just realized you already opened a PR @dprotaso :woman_facepalming: i'll move this feedback over there, it'd be great to see more detail in the commit messages there

**Comment by bobcatfish** [comment]
Note just in case someone comes across this later: I ran into trouble after this change because my `kubectl` was too old and there was some outdated client side validation that failed, so I needed to update `kubectl`.
