### ISSUE TITLE
Design: References

### ISSUE THREAD

**Issue by aaron-prindle** [knative/build-pipeline#38]
Create a separate design doc which explores in detail how references will work between our resources, e.g.:

- TaskRuns refer to Tasks
- PipelineRuns refer to Pipelines and PipelineParams
- Pipelines refer to Tasks when linking Task outputs with Inputs

Documentation:
https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#references-to-related-objects

**Comment by shashwathi** [comment]
Is this design doc meant to also explain the contract between each resources?

**Comment by bobcatfish** [comment]
@shashwathi ya to some extent! we might see more detail in some of [the other upcoming designs](https://github.com/knative/build-pipeline/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+design) tho, this doc would be focused on specifically the mechanics of how to express these references

**Comment by bobcatfish** [comment]
[This is the design doc for both templating and references](https://docs.google.com/document/d/1bJLE1E6skPjr1rGtSR0gAXdMaWryXTDTVnCPIKJkRBk), shared with members of  [knative-dev@](https://groups.google.com/forum/#!forum/knative-dev).

See also #36
