### ISSUE TITLE
Use storage bucket to link outputs and inputs of tasks

### ISSUE THREAD

**Issue by pivotal-nader-ziada** [knative/build-pipeline#384]
## Expected Behavior
 * Currently the PipelineRun controller uses a PVC (Persistent volume claim) to link artifacts from the output of a task to the input of the following task. 
 * Due to the nature of PVC having different implementation on different platforms, the system should also support using a cloud storage bucket, for example a gcs bucket, to achieve the same functionality. 
 * The storage bucket should be configured by the user as part of the `PipelineRun`

## Actual Behavior
Only PVCs are supported

## Additional Info
related to #148

**Comment by bobcatfish** [comment]
Crazy (probably bad) idea: could it also make sense to have an option where if task X's outputs are linked to task Y's inputs, we schedule them on the same node and use an emptydir volume to share data between them?

**Comment by pivotal-nader-ziada** [comment]
I don't think you can share `emptydir` volume across pods
