### ISSUE TITLE
Update DEVELOPMENT.md since the ./third_party/config/build/release.yaml has been removed.

### ISSUE THREAD

**Issue by zhyuri** [knative/build-pipeline#390]
Please correct me if I missed something.

The file `./third_party/config/build/release.yaml` was added in the repo by commit https://github.com/knative/build-pipeline/commit/d2a68252ea544e6f1eadb4b17468dad7d080b687.

After the PR https://github.com/knative/build-pipeline/pull/326, the file has been deleted. We should update [DEVELOPMENT.md](https://github.com/knative/build-pipeline/blob/master/DEVELOPMENT.md#install-pipeline) and remove related lines.

## Expected Behavior

Two lines of command related to the file `./third_party/config/build/release.yaml` should be removed.

## Actual Behavior

I was confused about the document because I can't find this yaml in the repo.

**Comment by bobcatfish** [comment]
You are totally right @zhyuri , thanks for following up on this and sorry for the confusion!

**Comment by bobcatfish** [comment]
Thanks for again for fixing this @zhyuri 😭 !!!
