### ISSUE TITLE
Private GCS buckets credentials

### ISSUE THREAD

**Issue by Conky5** [knative/build-pipeline#402]
## Expected Behavior

Private GCS storage resources should be accessible with a properly configured `GOOGLE_APPLICATION_CREDENTIALS`.

## Actual Behavior

A `AccessDeniedException: 403 Insufficient OAuth2 scope to perform this operation.` error is encountered.

## Steps to Reproduce the Problem

1. Configure a private GCS storage resource as described in https://github.com/knative/build-pipeline/blob/master/docs/using.md#gcs-storage-resource
2. Attempt to use it in an input to a task and taskrun.

## Additional Info

`gcloud` and `gsutil` do not consume the `GOOGLE_APPLICATION_CREDENTIALS` environment variable https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/152. A `gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS` before invoking `gsutil` should do it.

**Comment by mgreau** [comment]
I've started [working on a fix here](https://github.com/mgreau/build-pipeline/commit/2021783dd958054fe9cf5cc2584d5b731b9c1e09), this is still WIP.

**Comment by bobcatfish** [comment]
oh noes i think this might also be addressed by https://github.com/knative/build-pipeline/pull/404 @mgreau @shashwathi !!

i think the solutions are pretty similar (great minds think alike!) but probably you dont have to keep working on this @mgreau 

(sorry for not noticing this was a duplicate of #372 sooner!!)

**Comment by mgreau** [comment]
@bobcatfish no worries! I'm happy that this bug is close to being fixed 👍

**Comment by Conky5** [comment]
Hi @shashwathi, it works! Thanks 😄

**Comment by shashwathi** [comment]
Thank you for testing this and providing feedback. I appreciate it
