### ISSUE TITLE
PipelineValidationFailed and yet my PipelineRun is reported as having succeeded

### ISSUE THREAD

**Issue by a-roberts** [knative/build-pipeline#429]
I'm seeing an error running the examples on my laptop, getting the PipelineRun information itself confuses me...

## Expected Behavior
When there's an issue, e.g. we see this from a PipelineRun:
```
  status:
    conditions:
    - lastTransitionTime: 2019-01-24T11:02:37Z
      message: 'invalid output resources: TaskRun''s declared resources didn''t match
        usage in Task: Didn''t provide required values: [builtImage]' (extra apostrophes here too)
      reason: PipelineValidationFailed
      status: "False"
      type: Succeeded
    conditions:
    - lastTransitionTime: 2019-01-24T11:02:37Z
      message: 'invalid output resources: TaskRun''s declared resources didn''t match
        usage in Task: Didn''t provide required values: [builtImage]'
      reason: PipelineValidationFailed
      status: "False"
      type: Succeeded
```
it should surely be type: Failed as opposed to Succeeded? Or is this the status of the validator doing its job? Either way it's counter intuitive and potentially a bug here.

## Actual Behavior
type is `Succeeded`. My controller logs report the pipeline run was successful.

## Steps to Reproduce the Problem

1. Clone this repository, ko apply to build the images, follow the tutorial using pipelines
2. `kubectl apply -f examples/`
    `kubectl apply -f examples/run/pipeline-run.yaml`
3. `kubectl get pipelinerun -o yaml`

## Additional Info
1) Is this really intended behaviour? Are we missing a check to see if validation failed, throw an error?
2) The root cause of the problem: are the examples incorrect?

**Comment by a-roberts** [comment]
Thanks, I see `For objects which run to completion, the condition type should be Succeeded.`: so this means the run did "Succeed" in that it run to completion, and the validation failed as we see from the message which indeed indicates a problem in the example?

If so let's close this one off and I'll take a look at the invalid output resource message.

**Comment by vdemeester** [comment]
> Thanks, I see `For objects which run to completion, the condition type should be Succeeded.`: so this means the run did "Succeed" in that it run to completion, and the validation failed as we see from the message which indeed indicates a problem in the example?

Yes :angel: The run succeeded to complete but the status is `False`, meaning it failed. It's completed but failed :angel:.

/close
