### ISSUE TITLE
Cluster resource cannot be used if the cluster name is not DNS-1123 subdomain

### ISSUE THREAD

**Issue by afrittoli** [knative/build-pipeline#431]
## Expected Behavior

My cluster name contains an underscore e.g. `my_cluster`. I should be able to define a cluster resource to use that.

## Actual Behavior

Cluster name is taken from the resource metadata `name`, so it can only be set a valid DNS-1123 subdomain. 

`The PipelineResource "xyz" is invalid: metadata.name: Invalid value: "my_cluster": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

Defaulting the cluster name to the resource name makes sense, but there should be a parameter to override that.

## Steps to Reproduce the Problem

1. Create a cluster resource called `my_cluster`

## Additional Info
https://github.com/knative/build-pipeline/blob/master/pkg/apis/pipeline/v1alpha1/cluster_resource.go#L57

**Comment by bobcatfish** [comment]
whoops, good catch @afrittoli !
