### ISSUE TITLE
Use "AppendRandomString" function from knative/pkg

### ISSUE THREAD

**Issue by odra** [knative/build-pipeline#490]
## Expected Behavior

No errors - just remove the implementation of `AppendRandomString` and use the one implemented on knative/pkg (`test module`) once this PR gets merged: https://github.com/knative/pkg/pull/256

## Actual Behavior

No errors, see above item.

## Steps to Reproduce the Problem

No errors, see above item.

## Additional Info

https://github.com/knative/pkg/pull/256

**Comment by bobcatfish** [comment]
Hey @odra ! In https://github.com/knative/build-pipeline/pull/491 we're actually deleting `AppendRandomString` and using https://github.com/knative/build-pipeline/blob/244e1cbf464589501923b863ca94dea39b6468a6/pkg/names/generate.go instead
