### ISSUE TITLE
Setup continuous integration for build-pipeline

### ISSUE THREAD

**Issue by bobcatfish** [knative/build-pipeline#52]
## Expected Behavior
In addition to running tests against pull requests, and especially once we get #16 (integration tests) added, we should have our tests running continually to be sure nothing breaks over time (e.g. some kind of issue with a dependency - as much as we want our tests to be hermetic they probably never will be 100%).

Our pull request tests:
* https://prow.knative.dev/?job=pull-knative-build-pipeline-unit-tests
* https://prow.knative.dev/?job=pull-knative-build-pipeline-build-tests

We should also update the tags in our README to use these so they won't turn red every time someone's PR breaks :sweat_smile: 

## Actual Behavior
We currently have tests which run on PRs only, but no continuous integration.

## Additional Info

This is an example of continuous integration for knative/serving:
https://prow.knative.dev/?job=ci-knative-serving-continuous

**Comment by adrcunha** [comment]
The integration tests job is now running:

https://github.com/knative/build-pipeline/pull/87

However, it's not marked as required (actually, none of the test jobs). I recommend doing it ASAP, as it means that your PRs are being merged ignoring any test failures.

**Comment by pivotal-nader-ziada** [comment]
@bobcatfish what do we need to do here?

**Comment by bobcatfish** [comment]
@pivotal-nader-ziada so we have jobs to run on PR at the moment, but we don't yet have anything to run continuously, e.g. once an evening. It's debatable whether we really need this - certainly the status of the unit tests should never change, but it _could_ be nice to know that the integration tests continue working.

That way if we all stopped working on the project for a while (e.g. over the holidays), we'd know it was still building and green when we get back.

And we can show the status of that job in our README, v.s the status of the jobs which are subject to PR failure.

**Comment by pivotal-nader-ziada** [comment]
Would be nice to have to give us confidence about the state of the tests.

**Comment by bobcatfish** [comment]
I'm going to close this for now, I think we feel pretty confident without it, but feel free to re-open if you disagree.
