### ISSUE TITLE
Installing Tekton Pipelines guide is not working

### ISSUE THREAD

**Issue by hrishin** [knative/build-pipeline#541]
As mentioned in [installation guide](https://github.com/knative/build-pipeline/blob/master/docs/install.md#adding-the-tekton-pipelines) step 1, `release.yaml` is not present on the release bucket.

## Expected Behavior
```
kubectl apply --filename https://storage.googleapis.com/tekton-pipeline-releases/latest/release.yaml
```
Should install Tekton pipeline resources

## Actual Behavior

```
$ kubectl apply --filename https://storage.googleapis.com/tekton-pipeline-releases/latest/release.yaml
error: unable to read URL "https://storage.googleapis.com/tekton-pipeline-releases/latest/release.yaml", server reported 404 Not Found, status code=404
```

## Steps to Reproduce the Problem

1. kubectl apply --filename https://storage.googleapis.com/tekton-pipeline-releases/latest/release.yaml

## Additional Info

Maybe release is broken?

**Comment by vdemeester** [comment]
I think the release is not yet published on that bucket (cc @ImJasonH @bobcatfish) and still is on knative release bucket https://storage.googleapis.com/knative-releases/build-pipeline/latest/release.yaml it seems :angel:

**Comment by pivotal-nader-ziada** [comment]
yes, the release is in `gs://knative-releases/build-pipeline/latest/release.yaml`

**Comment by pivotal-nader-ziada** [comment]
created a PR to fix the file path for now

**Comment by bobcatfish** [comment]
Thanks for the detailed report @hrishin - and the quick fix @pivotal-nader-ziada !! :heart:

**Comment by bobcatfish** [comment]
(Will be creating Tekton specific buckets etc. in https://github.com/knative/build-pipeline/issues/527)
