### ISSUE TITLE
Add a step to verify vendor code before running unit tests.

### ISSUE THREAD

**Issue by tejal29** [knative/build-pipeline#77]
## Expected Behavior
On a Branch, we would want developers to run dep ensure, so that unused dependencies are removed.
We can do this by running a [script](https://github.com/grafeas/kritis/blob/master/hack/dep.sh) in the checks which runs dep ensure and check if they are any changes to vendor dir.

## Actual Behavior
Right now, developers can easily add unused deps and overlook the libs pulled in since they tend to do this
```
git add vendor/
```

## Steps to Reproduce the Problem
none

**Comment by tejal29** [comment]
This should also run ./hack/update-dep.sh and ./hack/update-code-gen.sh

**Comment by tejal29** [comment]
We should also run verify-code-gen in CI and error if there any changes to vendor-ed code. https://github.com/grafeas/kritis/blob/master/hack/verify-codegen.sh

**Comment by bobcatfish** [comment]
knative projects have a bunch of scripts in [`hack`](https://github.com/knative/build-pipeline/tree/master/hack) that get copied around into all the repos for this, and it seems like there are more in the test-infra bash scripts.

[verify-codegen.sh](https://github.com/knative/build-pipeline/blob/master/hack/verify-codegen.sh) is the script that makes sure dep is a no-op.
